allowBuilds:
  '@clerk/shared': true
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  esbuild: true
  sharp: true

ignoredBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@tailwindcss/oxide'
  - sharp
